server:
    port: 8855
spring:
  datasource:                           # postgres in prod
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./test;
  jpa:
    hibernate:
      ddl-auto: create                  # update in prod
